<?php

namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20230509153758 extends AbstractMigration
{
    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE avency_neos_importer_domain_model_importversion (persistence_object_identifier VARCHAR(40) NOT NULL, importversion VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE avency_neos_importer_domain_model_importdata ADD importversion VARCHAR(40) DEFAULT NULL, DROP importtimestamp');
        $this->addSql('ALTER TABLE avency_neos_importer_domain_model_importdata ADD CONSTRAINT FK_AD96332E3A1E8E58 FOREIGN KEY (importversion) REFERENCES avency_neos_importer_domain_model_importversion (persistence_object_identifier)');
        $this->addSql('CREATE INDEX IDX_AD96332E3A1E8E58 ON avency_neos_importer_domain_model_importdata (importversion)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE avency_neos_importer_domain_model_importdata DROP FOREIGN KEY FK_AD96332E3A1E8E58');
        $this->addSql('DROP TABLE avency_neos_importer_domain_model_importversion');
        $this->addSql('DROP INDEX IDX_AD96332E3A1E8E58 ON avency_neos_importer_domain_model_importdata');
        $this->addSql('ALTER TABLE avency_neos_importer_domain_model_importdata ADD importtimestamp VARCHAR(255) CHARACTER SET utf8 DEFAULT \'\' NOT NULL COLLATE `utf8_unicode_ci`, DROP importversion');
    }
}
